[workspace]
exclude = [
  # "rust/fhir",
]
members = [
  "rust/codegen",
  "rust/fhir",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
